import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const THEME_SCRIPT = `
(function () {
  try {
    var mql = window.matchMedia('(prefers-color-scheme: dark)');
    var apply = function (isDark) {
      document.documentElement.setAttribute('data-bs-theme', isDark ? 'dark' : 'light');
    };
    apply(mql.matches);
    mql.addEventListener('change', function (e) { apply(e.matches); });
  } catch (e) {}
})();
`;

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body>{children}</body>
    </html>
  );
}